version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sahi-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vaultpass_platform
      POSTGRES_USER: vaultpass
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vaultpass -d vaultpass_platform"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sahi-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mqtt:
    image: eclipse-mosquitto:2
    container_name: sahi-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquittodata:/mosquitto/data
      - mosquittolog:/mosquitto/log

volumes:
  pgdata:
  redisdata:
  mosquittodata:
  mosquittolog:
