import 'dart:typed_data';

import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Crypto service using flutter_rust_bridge FFI to crypto-engine.
///
/// All cryptographic operations are delegated to Rust.
/// ZERO Dart crypto per spec - all via FFI bridge.
///
/// Note: The actual FFI bindings are generated by flutter_rust_bridge
/// from the Rust code in apps/wallet/rust/. This file provides
/// the Dart wrapper interface.
class CryptoService {
  // In production, these would call into the Rust FFI bridge.
  // For now, we define the interface that the bridge will implement.

  /// Create a Verifiable Presentation from an SD-JWT credential.
  ///
  /// Parameters:
  /// - [sdJwt]: The SD-JWT credential
  /// - [nonce]: Challenge nonce from the verifier
  /// - [disclosedClaims]: Claims to selectively disclose
  ///
  /// Returns the VP as bytes (CBOR-encoded for NFC, JSON for BLE).
  Future<Uint8List> createPresentation({
    required String sdJwt,
    required Uint8List nonce,
    required List<String> disclosedClaims,
  }) async {
    // TODO: Call Rust FFI bridge
    // return await bridge.createPresentation(sdJwt, nonce, disclosedClaims);
    throw UnimplementedError('FFI bridge not yet generated');
  }

  /// Sign data with the device key.
  ///
  /// This creates a key binding JWT for the presentation.
  Future<Uint8List> signWithDeviceKey(Uint8List data) async {
    // TODO: Call Rust FFI bridge
    // return await bridge.signWithDeviceKey(data);
    throw UnimplementedError('FFI bridge not yet generated');
  }

  /// Verify an SD-JWT credential.
  ///
  /// Checks:
  /// - Signature validity
  /// - Issuer DID resolution
  /// - Expiration
  /// - (Does NOT check revocation - that's SyncService's job)
  Future<bool> verifyCredential(String sdJwt) async {
    // TODO: Call Rust FFI bridge
    // return await bridge.verifyCredential(sdJwt);
    throw UnimplementedError('FFI bridge not yet generated');
  }

  /// Parse an SD-JWT to extract claims.
  Future<Map<String, dynamic>> parseCredential(String sdJwt) async {
    // TODO: Call Rust FFI bridge
    // return await bridge.parseCredential(sdJwt);
    throw UnimplementedError('FFI bridge not yet generated');
  }

  /// Encode presentation payload as CBOR for NFC.
  ///
  /// CBOR is 40-60% smaller than JSON per spec.
  Future<Uint8List> encodeAsCbor(Map<String, dynamic> payload) async {
    // TODO: Call Rust FFI bridge
    // return await bridge.encodeAsCbor(payload);
    throw UnimplementedError('FFI bridge not yet generated');
  }

  /// Decode CBOR payload.
  Future<Map<String, dynamic>> decodeCbor(Uint8List cbor) async {
    // TODO: Call Rust FFI bridge
    // return await bridge.decodeCbor(cbor);
    throw UnimplementedError('FFI bridge not yet generated');
  }

  /// Parse a status list credential to check revocation status.
  Future<bool> checkRevocationStatus({
    required String statusListCredential,
    required int index,
  }) async {
    // TODO: Call Rust FFI bridge
    // return await bridge.checkRevocationStatus(statusListCredential, index);
    throw UnimplementedError('FFI bridge not yet generated');
  }

  /// Generate a DID:key from a public key.
  Future<String> generateDidKey(Uint8List publicKey) async {
    // TODO: Call Rust FFI bridge
    // return await bridge.generateDidKey(publicKey);
    throw UnimplementedError('FFI bridge not yet generated');
  }
}

/// Provider for crypto service.
final cryptoServiceProvider = Provider<CryptoService>((ref) {
  return CryptoService();
});
